[package]
name = "wombo_model"
version = "0.1.0"
authors = ["Matteo Nardi <commits@matteonardi.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xkbcommon = "0.4.0"
evdev = "0.11.0"
