[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
gio = "0.15.12"
gtk = { version = "0.4.8", package = "gtk4", features = ["v4_6"]}

[build-dependencies]
gtk = { version = "0.4.8", package = "gtk4", features = ["v4_6"]}
